#!/bin/sh

# forge test

forge test \
    --match-test testFailNonOwnerCannotSettleOngoingEpoch \
    --match-contract Contract

forge test \
    --match-test testCannotSettleOngoingEpoch \
    --match-contract Contract

forge test \
    --match-test testSettleEndedEpoch \
    --match-contract Contract