#!/bin/sh

forge test -vv

# forge test \
#     --match-test testFailNonOwnerSettleOngoingEpoch \
#     --match-contract Contract

# forge test \
#     --match-test testCannotSettleOngoingEpoch \
#     --match-contract Contract

# forge test \
#     --match-test testSettleEndedEpoch \
#     --match-contract Contract

# forge test \
#     --match-test testFailDepositAfterClose \
#     --match-contract Contract

# forge test \
#     --match-test testFailDepositInsufficientAmount \
#     --match-contract Contract

# forge test \
#     --match-test testDepositBull \
#     --match-contract Contract

# forge test \
#     --match-test testDepositBear \
#     --match-contract Contract

# forge test \
#     --match-test testWinnerWithdraw \
#     --match-contract Contract

# forge test -vvv \
#     --match-test testLoserWithdraw \
#     --match-contract Contract

# forge test -vv \
#     --match-test testRolloverBet \
#     --match-contract Contract
